atlanteti/bfree-webui

- src/Componentes/DefaultValidateInputs/DefaultValidationTextField.js
- src/Componentes/PhoneInput/index.js
- src/Pages/Demandas/Cadastrar/Form.js
Campo de telefone estava implicitamente usando a propriedade required e estava sendo definido como obrigatório na página errada.
Função usada para controlar inserção de dados nos campos estava com nome errado
> Resolve b10t342

- src/Componentes/PhoneInput/index.js
O componente era incapaz de aceitar preenchimento vazio, como por exemplo na tela de cadastro de demanda ou usuário.
Agora a lógica condicional faz checagens de sanidade para certificar que está acessando atributos que existem
https://trello.com/c/vf9wcDod/347-campo-de-telefone-n%C3%A3o-aceitava-preenchimento-vazio
> Bug(Componente): Entrada de telefone agora aceita preenchimento vazio

- src/Componentes/PhoneInput/index.js
Quando o campo é parcialmente preenchido e tentava enviar, a formatação mudava
Adiciona uma nova condicional para que isso não aconteça
https://trello.com/c/4M0ng7oP/350-telefone-%C3%A9-formatado-incorretamente-ao-tentar-enviar-um-formul%C3%A1rio-inv%C3%A1lido-e-o-preenchimento-do-telefone-est%C3%A1-incompleto
> Bug(Componente): Campo de telefone alterava formatação de forma errada

- src/Componentes/DefaultValidateInputs/DefaultValidationTextField.js
- src/Componentes/PhoneInput/index.js
- src/Pages/Demandas/Cadastrar/Form.js
- src/Pages/Usuarios/Cadastrar/Form.js
- src/Services/validations.js
Página de demandas não validava campo de email, agora valida.
Tradução da mensagem de erro da validação centralizada em um arquivo separado.
Comparação incompleta no componente de telefone atualizada para ser capaz de receber undefined ou null no campo que define seu conteúdo.
> Resolve rejeição de b10t330

- src/Componentes/DefaultValidateInputs/DefaultValidationTextField.js
Quando o yup e o servidor marcavam um campo como inválido, o componente entrava em um loop de renderização e travava a aplicação
> Bug(Componente): Prioriza recebimento de mensagem de campo errado do servidor

- src/Componentes/CustomAlert/index.js
Adiciona verificação pra quando o componente de alerta tenta acessar o ref usado para fazer scroll na página
https://trello.com/c/mU7OFZ9N/366-aplica%C3%A7%C3%A3o-quebra-quando-um-usu%C3%A1rio-comum-acessa-e-n%C3%A3o-tem-registros-na-p%C3%A1gina-de-demanda
> Bug(Componente): Alerta tenta acessar ref inexistente

- src/Pages/Demandas/Listar/index.js
Mostra dia e hora da reunião no lugar da coluna de email, permite filtragem pelo dia e hora da reunião
Card relacionado: https://trello.com/c/0BkHjCU6/423-feature-exibir-a-data-hora-do-agendamento-para-o-consultor
> Resolve b10t423

- src/Pages/Demandas/Cadastrar/Form.js
Ajustado caso em que a demanda não era salva quando o status mudava para Descarte
O seletor de data de reunião não aparece para os status em aberto e descarte
card relacionado: https://trello.com/c/qne1Ac1P/431-bug-n%C3%A3o-conseguimos-alterar-o-status-de-em-aberto-para-descarte
> Resolve b10t431

- src/Pages/Demandas/Cadastrar/Form.js
Ajusta o caso em que o usuário que tinha as duas jornadas não conseguia remarcar uma reunião 
card relacionado: https://trello.com/c/rLcxHZUg/438-feature-bloquear-a-data-de-a%C3%A7%C3%A3o-para-pr%C3%A9-consultores-e-consultores
> resolve b10t436

- src/Componentes/ListData/index.js
- src/styles/CommonStyles.js
Resolvido o caso em que a tela bugava ao não ter nenhum valor registado na tabela e que a exibição dos dados para mobile ficava desalinhada
card relacionado: https://trello.com/c/x2L5EwOr/441-bug-bug-visual-no-grid-de-demanda-no-firefox
> resolve b10t441

- src/Pages/Demandas/Cadastrar/Form.js
Ao alterar o status de uma demanda que já tinha um histórico, não estava sendo passado para a data de ação o dia atual, e sim o primeiro dia do histórico
card relacionado: https://trello.com/c/HWsRBtLD/445-bug-data-de-a%C3%A7%C3%A3o-n%C3%A3o-de-acordo-com-o-que-foi-requisitado
> resolve b10t445

- src/Pages/Demandas/Cadastrar/Form.js
Ajustado bug que crashava tela ao selecionar o valor Agendando em Status de Demanda
card relacionado: https://trello.com/c/aBH0pSnw/463-bug-ao-alterar-o-status-para-agendado-a-tela-de-demanda-est%C3%A1-crashando
> resolve b10t463

- src/Pages/Demandas/Cadastrar/Form.js
Adicionado atributo que faz com que a data mínima seja o dia atual
card relacionado: https://trello.com/c/VS7EK0eS/475-bug-est%C3%A1-sendo-poss%C3%ADvel-agendar-uma-data-de-reuni%C3%A3o-inferior-a-data-atual
> resolve b10t475

- .env.development
- .env.staging
- src/Pages/Demandas/Cadastrar/Form.js
- src/Services/api.js
Card relacionado: https://trello.com/c/1OaZHs52/491-agendar-reuni%C3%A3o-sem-enviar-o-hor%C3%A1rio-final-e-usar-o-hor%C3%A1rio-que-o-back-manda-para-mostrar-a-hora-da-reuni%C3%A3o
Para testar: Vá em uma demanda em aberto e mude para agendado, tente marcar uma reunião num horário disponível
> Resolve b10t491

- src/Pages/Log/index.js
Adicionado condicionais para o caso em que no log mostra os dados de Inicio e Fim
Os atributos tão retornado de duas formas, um em forma de string e o outro em formato de data, isso que estava gerando o erro
card relacionado: https://trello.com/c/dSOO9RE4/497-bug-exibi%C3%A7%C3%A3o-dos-dados-do-calend%C3%A1rio-de-forma-incorreta
> resolve b10t497

- src/Pages/Demandas/Cadastrar/Form.js
Solucionado o caso em que o useEffect ficava tentando montar a aplicação mais vezes que o necessário
card relacionado: https://trello.com/c/X01zFaU7/458-refactor-ao-editar-uma-demanda-a-aplica%C3%A7%C3%A3o-est%C3%A1-fazendo-muitas-requisi%C3%A7oes
> resolve b10t458

- src/Componentes/CustomMenu/index.js
Ajustado menu para quando a tela era muito grande
Foi feita algumas alterações também para que ficasse mais justo em outros tamanhos de tela
card relacionado: https://trello.com/c/Tw5Rwh2d/529-o-espa%C3%A7o-entre-o-grid-e-o-menu-lateral-fica-muito-grande-em-monitores-maiores
> resolve b10t529

- src/Pages/Demandas/Cadastrar/Form.js
Formata o dem_dtacion para enviar apenas data sem horário
card relacionado: https://trello.com/c/N9AvXKut/495-bug-verificar-quando-o-fuso-do-navegador-%C3%A9-diferente-porque-a-data-enviada-est%C3%A1-diferente
> resolve b10t495

- package.json
- src/Componentes/ListData/index.js
Os downloads das planilhas nao estavam funcionando, teve que ser adicionado o pacote do buffer para normalizar
card relacionado: https://trello.com/c/Q9F7XJSz/535-bug-n%C3%A3o-est%C3%A1-sendo-poss%C3%ADvel-fazer-o-download-dos-excel
> resolve b10t535

- src/Componentes/CustomMenu/index.js
O menu passa a ter um tamanho fixo
card relacionado: https://trello.com/c/eZ41dyO2/543-bug-espa%C3%A7amento-lateral-do-relat%C3%B3rio-de-produtividade
> resolve b10t543

- src/Pages/DadosBancarios/Cadastrar/Form.js
Adicionado a mascara no cpf quando o usuário ja tem dado cadastrado
card relacionado: https://trello.com/c/TMtvvIXZ/553-bug-n%C3%A3o-est%C3%A1-sendo-adicionada-a-mascara-no-cpf-quando-o-usu%C3%A1rio-olha-os-dados-banc%C3%A1rios
> resolve b10t553

- src/Pages/DadosBancarios/Cadastrar/Form.js
Os campos de dados bancários são desativados para usuários ADM
card relacionado: https://trello.com/c/9lshuZgx/554-feature-desabilitar-os-campos-dos-dados-banc%C3%A1rios-para-quando-o-usu%C3%A1rio-for-adm
> resolve b10t554

- src/styles/CommonStyles.js
Ajustado caso que só aparecia um ícone das ações para mobile
card relacionado: https://trello.com/c/F7SEOPqk/557-bug-no-layout-responsivo-o-grid-n%C3%A3o-exibe-o-%C3%ADcone-da-lixeira
> resolve b10t557

- src/Componentes/ListData/index.js
- src/Pages/Relatorio/Listar/index.js
Adicionado condicional para quando a tela é de relatorios
A tela só deve carregar os dados quando houver o submit do buscar
card relacionado: https://trello.com/c/eKCPqlO6/561-alterar-o-comportamento-do-relat%C3%B3rio-de-billing
> resolve b10t561

- src/Pages/Demandas/Cadastrar/Form.js
Adicionado obrigatoriedade no campo de Codigo do Usuário
Ele é obrigatorio e nao estava possivel criar demanda sem adicionalo
> fix b10t566

- src/Pages/Demandas/Cadastrar/Form.js
Não estava sendo possivel criar uma demanda, pois a data açao estava sendo enviada como invalida, quando a data era nula
card relacionado: https://trello.com/c/u3pY3Xbu/587-personalizar-mensagem-de-erro-da-data-de-a%C3%A7%C3%A3o
> resolve b10t587

- src/Componentes/FormikComponents/PhoneInput.js
Só aparece o botao quando ta no DemandForm 
Remove caracteres para que nao bug o link quando for redirecionado
card relacionado: https://trello.com/c/6X9JmG1L/585-feature-implementar-o-link-para-conversa-pelo-whats-app-diretamente
> fix b10t585

- src/Pages/Relatorio/Listar/index.js
Agora a linha total dos relátorios informam todo o total de valores da tabela
Com a nova implementação, de ser enviado 10 por página, verifica só os dá pagina atual
card relacionado: https://trello.com/c/AHYmJJWe/589-refactor-ajustar-o-valor-total-no-relat%C3%B3rio
> resolve b10t589

- src/Pages/Horarios/utils.js
- src/styles/CommonStyles.js
Arruma caso em que para mobile ao clicar na linha do botao ia para outra pagina
card relacionado: https://trello.com/c/6SqOk7vf/612-refactor-organizar-a-tela-de-agendas-para-quando-a-resolu%C3%A7%C3%A3o-for-para-mobile
> resolve b10t610

- src/Pages/Horarios/Calendario/utils.js
- src/Pages/Horarios/utils.js
Resolve caso em que ao adicionar mais de um horario do final para o inicio, bugava ao enviar
Resolvido caso em que o seletor ficava congelado ao selecionar o horario final na tela de calendario(caso o item não fosse o primeiro) 
card relacionado: https://trello.com/c/9bfABzx3/615-hor%C3%A1rios-em-conflito-no-envio-da-requisi%C3%A7%C3%A3o
> resolve b10t615

- src/Componentes/HourComponent/index.js
- src/Pages/Horarios/Calendario/index.js
Ajusta caso em que um seletor ficava maior que o outro para um certo tipo de tela
Ajusta o calendario para quando a tela do celular for pequena
card relacionado: https://trello.com/c/6SqOk7vf/612-refactor-organizar-a-tela-de-agendas-para-quando-a-resolu%C3%A7%C3%A3o-for-para-mobile
> resolve b10t612

- src/Services/api.js
Adiciona caso em que quando o consultor não tem os dados cadastrado redireciona para a tela de cadastrar dados
card relacionado: https://trello.com/c/UqyRQxzE/625-feature-bloquear-o-uso-do-sistema-se-o-usu%C3%A1rio-n%C3%A3o-houver-preenchido-os-dados-banc%C3%A1rios
> resolve b10t625

- src/Componentes/CustomMenu/index.js
Resolve caso em que ao clicar nos submenus o scroll das paginas travavam para resoluções mobile
card relacionado: https://trello.com/c/mZyV4zeb/627-bug-aplica%C3%A7%C3%A3o-travando-para-mobile-quando-o-usu%C3%A1rio-%C3%A9-consultor-pre
> resolve b10t627

- src/Componentes/SearchBar/index.js
Corrigi caso em que ao adicionar data no Status Comparecido, não enviava o arquivo enviando a data
Corrigi caso em que ao adicionar a data e alterar para outro status, a data continuava sendo enviada
card relacionado: https://trello.com/c/czYLQioy/636-refactor-adicionar-os-valores-das-datas-ao-fazer-download-da-planilha-em-comparecido
> resolve b10t636
