atlanteti/bfree-webui

- src/Pages/Times/Listar/index.js
- src/Pages/Usuarios/Listar/index.js
- src/Pages/Usuarios/UsuarioTimes/index.js
- src/index.js
> feat: criada tela de usuário x times

- .gitignore
- src/Services/api.js
configurar a url base da API do servidor
> API de requisição precisa que um arquivo config.js seja criado para 

- src/App.js
- src/Componentes/CustomMenu/index.js
para a página inicial, documenta a assinatura da função de login como comentário no App.js
> Usa o redirecionamento implementado pelo logout da eduzz para retornar

- src/Pages/Times/TipoMentores/index.js
> Muda opção "Nenhum" para um campo vazio, seguindo a interface estabelecida

- src/Componentes/DateField/index.js
Adicionada condicional para caso de borda quando se quer renederizar apenas data
> Resolve rejeição de b10t279

- src/Componentes/FormFields/index.js
adiciona validação para quando campo estiver vazio
> Adiciona mensagem enviada pelo servidor a subtexto do campo de entrada,

- src/Pages/Demandas/Cadastrar/Form.js
Em aberto(cód de status 1) para Descarte(cód de status 5)
> Usuário operador pode mover de em aberto para descarte 

- src/Componentes/FormFields/index.js
- src/Pages/Companhia/Cadastrar/Form.js
props padrão foram extraídos para um componente base e reutilizados entre os componentes afetados
> Inputs são validados quando o botão de submeter é clicado,

- src/Componentes/DefaultValidateInputs/DefaultValidateSelectField.js
- src/Componentes/DefaultValidateInputs/DefaultValidationTextField.js
- src/Componentes/FormFields/index.js
- src/Componentes/ListCompanies/index.js
- src/Pages/Jornadas/Cadastrar/Form.js
Permite validação ao clicar na página de cadastro de jornada, extrai os componentes de validação e props padrão para o próprio diretório
> Resolve b10t322

- src/Componentes/FormFields/index.js
- src/Pages/Times/Cadastrar/Form.js
Componente genérico para seletor de campo com Ativo/Inativo Verdadeiro/Falso atualizado para validar e destacar
> Página de times valida campos

- src/Pages/Demandas/Listar/index.js
- src/styles/CommonStyles.js
Como eu ja tinha reajustado no ticket 285, nesse ticket adicionei apenas no campo de email, que estava quebrando a tela com alguns emaisl grandes.
> fix: Adicionado estilo de elipse para campo de email

- src/Componentes/ActionDatePicker/index.js
- src/Componentes/DefaultValidateInputs/DefaultValidateSelectField.js
- src/Componentes/EditCreateForm/index.js
- src/Componentes/FormFields/index.js
- src/Componentes/ListJourneysControlled/index.js
- src/Componentes/ListStatusDemands/index.js
- src/Componentes/ListTypeDemand/index.js
- src/Componentes/ListUserStatus/index.js
- src/Componentes/ListUsers/index.js
- src/Componentes/PhoneInput/index.js
- src/Pages/Demandas/Cadastrar/Form.js
- src/Pages/Times/Cadastrar/Form.js
- src/Pages/Usuarios/Cadastrar/Form.js
Cria alguns componentes novos para se adequar à ideia de reutilização
Reorganiza a ordem dos props das entradas da página para ficar consistente com o resto do código
Extrai funcionalidade repetida para componentes reutilizáveis
Valida os campos de acordo com a obrigatoriedade do seu preenchimento
Cards relacionados: https://trello.com/c/4kBIa1Hk/329-implementar-valida%C3%A7%C3%A3o-de-campos-do-formul%C3%A1rio-da-p%C3%A1gina-de-demandas
> Resolve b10t329

- src/Componentes/DefaultValidateInputs/DefaultValidationTextField.js
- src/Componentes/EditCreateForm/index.js
[Card relacionado](https://trello.com/c/NwNpKPmE/333-valida%C3%A7%C3%A3o-de-texto-fica-em-estado-inconsistente-depois-de-come%C3%A7ar-a-entrada-do-campo-com-espa%C3%A7o)
> Resolve b10t333

- src/Componentes/PhoneInput/index.js
Se o usuário só preencher 8 dígitos, fica (99) 9999-9999
Se o usuário preencher 9 dígitos, fica (99) 99999-9999
Nos campos de Telefone.
> Feature(Componente): Muda a máscara de acordo com o preenchimento

- package.json
- src/Componentes/DefaultValidateInputs/DefaultValidationTextField.js
- src/Pages/Usuarios/Cadastrar/Form.js
Usa a biblioteca de validação do Yup para validar emails já que existem regras demais para serem escritas manualmente
Card Relacionado: https://trello.com/c/1NZjxe5U/330-bug-indica%C3%A7%C3%A3o-de-erro-mesmo-ap%C3%B3s-o-e-mail-cadastrado-de-forma-incorreta
> Resolve b10t330

- package.json
- src/Componentes/FormikComponents/DatePickerField.js
- src/Componentes/FormikComponents/DefaultValidationTextField.js
- src/Componentes/FormikComponents/GenericFormBuilder.js
- src/Componentes/FormikComponents/GenericSelector.js
- src/Componentes/FormikComponents/ListStatusDemands.js
- src/Componentes/FormikComponents/ListTypeDemand.js
- src/Componentes/FormikComponents/ListUserStatus.js
- src/Componentes/FormikComponents/ListUsers.js
- src/Componentes/FormikComponents/PhoneInput.js
- src/Componentes/FormikComponents/StatusHistory.js
- src/Componentes/FormikComponents/Timestamps.js
Card relacionado: https://trello.com/c/VNeIN1oA/356-gerar-componentes-compat%C3%ADveis-com-formik-e-yup
A intenção dessa alteração é manter a mesma funcionalidade dos componentes, mas permitir que eles necessitem de menos props e sejam mais abertos a reutilização, devido a isso
> Resolve b10t356

- src/Pages/Demandas/Cadastrar/Form.js
- src/Pages/Demandas/Cadastrar/index.js
BREAKING CHANGE: Depende da aceitação dos PRs das branchs 356, 357, 358 e 359 para funcionar
Altera o funcionamento do paradigma de hierarquia para componentização, centralizando a funcionalidade e lógica de negócio relativa à página de demanda para um componente, usando Formik e Yup para validação em vez de usar a solução criada anteriormente
> Feat(Page): Refatora a página de demanda para usar yup e formik

- src/Pages/Usuarios/Cadastrar/Form.js
- src/Pages/Usuarios/Cadastrar/index.js
BREAKING CHANGE: Depende da aceitação dos PRs das branchs 356, 357, 358 e 359 para funcionar  Altera o funcionamento do paradigma de hierarquia para componentização, centralizando a funcionalidade e lógica de negócio relativa à página de demanda para um componente, usando Formik e Yup para validação em vez de usar a solução criada anteriormente
> Feat(Page): Refatora a página de demanda para usar yup e formik 

- src/Componentes/CustomAlert/index.js
- src/Componentes/ListData/index.js
- src/Pages/Badges/Cadastrar/index.js
- src/Pages/Demandas/Cadastrar/index.js
Usa Ref em vez de window.scroll, assim funcionando de forma agnóstica a browser, dependendo das limitações do React
> Refactor(Component): Extrai funcionalidade de rolagem para o componente de alerta

- src/Pages/Demandas/Cadastrar/Form.js
Cria um schema alternativa pra página de edição de demanda, já que alguns campos ficam desabilitados, suas validações são removidas
> Bug(Page): Remove validação de campos desabilitados na edição

- .env.development
- .env.production
- .env.staging
- package.json
- src/Componentes/ListData/index.js
- src/Componentes/MultiSelectForm/index.js
- src/Pages/Badges/Listar/index.js
- src/Pages/Companhia/Listar/index.js
- src/Pages/Demandas/Listar/index.js
- src/Pages/Jornadas/Listar/index.js
- src/Pages/Times/Listar/index.js
- src/Pages/Times/TipoMentores/index.js
- src/Pages/TipoDemanda/Listar/index.js
- src/Pages/Usuarios/Listar/index.js
- src/Routes/app.routes.js
- src/Routes/auth.routes.js
https://trello.com/c/0xm63cuA/365-possibilitar-deploy-de-v%C3%A1rios-builds-ao-mesmo-tempo
> Resolve b10t365

- src/Componentes/CustomMenu/index.js
Adiciona o sufixo necessário para retornar à raiz da aplicação
> Bug(CustomMenu): Redirecionamento incompleto no logout

- src/Pages/Horarios/index.js
Refactor(Horario): Alterada as constantes na condicional que reedireionava os valores para os arrays especifico
Fix(Horario): Adicionado timeout para atualizar estado do elemento
> Refactor(b10t371)

- src/Componentes/CustomMenu/index.js
- src/Context/ContextLogin.js
- src/Services/api.js
Aplicação checa a permissão do usuário para acessar páginas relevantes ao usuário
> b10t373 - Integrar tipos de usuário com página de horário

- src/Pages/Demandas/Cadastrar/Form.js
O parâmetro do moment HH:MM por alguma razão adicionava um minuto pro texto
> Bug(Demand): Resolve erro de mostrar hora da  reunião

- src/Pages/Demandas/Cadastrar/Form.js
O consultor é bloqueado de alterar a data de reunião
Apenas o pre-consultor e o adm tem essa permissão
card relacionado: https://trello.com/c/ocboRi3Y/436-feature-o-pr%C3%A9-consultor-deve-ter-a-permiss%C3%A3o-de-reagendar
> Resolve b10t436

- src/Componentes/ListData/index.js
- src/Pages/Demandas/Listar/index.js
Adiciona a coluna de avaliado e usa o grid do react-bootstrap pra dimensionar a tabela quando não tem espaço
> Resolve b10t430

- src/Componentes/ListData/index.js
- src/Pages/Relatorio/Listar/index.js
- src/Pages/RelatorioGerencial/index.js
Resolve b10t422, card relacionado: https://trello.com/c/ez5duw5X/442-bug-os-formul%C3%A1rios-n%C3%A3o-est%C3%A3o-sendo-exibidos-no-mesmo-padr%C3%A3o-de-in%C3%ADcio-na-tela
> Fix(ListData): Refatora a utilização do grid do bootstap pra resolver espaçamento irregular

- src/Componentes/ListData/index.js
Ao da merge da main na branch atual, houve um reversão de codigo
Essa branch corrigi o conflito da reversão
> revert b10t441

- src/Pages/Demandas/Cadastrar/Form.js
Corrigido o caso em que não mostrava os botões de transferência e não comparecido quando o usuário tinha as duas jornadas vinculadas 
card relacionado: https://trello.com/c/Rznr1pmN/439-feature-implementa%C3%A7%C3%A3o-do-tratamento-de-reuni%C3%A3o-n%C3%A3o-comparecida
> fix b10t439

- src/Pages/Demandas/Cadastrar/Form.js
Desativado temporariamente o botão de Transferência de Demanda
card relacionado: https://trello.com/c/LdNhL0jt/452-refactor-remover-o-bot%C3%A3o-de-transferir-na-tela-de-demandas-precisamos-montar-um-fluxo-para-que-a-fun%C3%A7%C3%A3o-esteja-ok
> resolve b10t452

- src/Pages/Demandas/Listar/Contato/index.js
Adicionada uma coluna na tabela de Contatos do pre-consultor
card relacionado: https://trello.com/c/gMRSphwk/451-feature-adicionar-coluna-de-avaliado-para-pr%C3%A9-consultor
> resolve b10t451

- src/Componentes/FormikComponents/ListMessageStatus.js
- src/Pages/Demandas/Cadastrar/Form.js
- src/Pages/Demandas/Listar/Contato/index.js
Card relacionado: https://trello.com/c/2nB1iie2/432-feature-flag-organizar-msg-01-02-03-descarte-n%C3%A3o-devemos-fazer-no-momento
> Feat(Contato pré consultor): Adiciona coluna e permite edição no formulário

- src/Pages/Demandas/Cadastrar/Form.js
Faltava renderização condicional no seletor de mensagem
> Resolve b10t432

- src/Pages/Demandas/Cadastrar/Form.js
Remove obrigatoriedade do campo de observações
> resolve b10t455

- package.json
- src/Pages/Demandas/Cadastrar/Form.js
Adicionado o campo de código de usuário no formulário de Demanda
card relacionado: https://trello.com/c/UcFi5Ldg/457-feature-adicionar-c%C3%B3digo-do-usu%C3%A1rio-na-tela-de-demanda
> resolve b10t457

- src/Pages/Demandas/Cadastrar/Form.js
desativa os campo de email e telefone quando estiver sendo criada uma demanda manualmente
card relacionado: https://trello.com/c/6nzsDwW9/456-refactor-desativar-email-e-telefone-no-formul%C3%A1rio-de-demanda
> resolve b10t456

- package.json
- src/App.js
- src/Componentes/ExclusionModal/index.js
- src/Componentes/ListData/index.js
- src/Componentes/MultiSelectForm/index.js
- src/Pages/Badges/Cadastrar/index.js
- src/Pages/Companhia/Cadastrar/index.js
- src/Pages/Demandas/Cadastrar/Form.js
- src/Pages/Demandas/Cadastrar/index.js
- src/Pages/Jornadas/Cadastrar/index.js
- src/Pages/Times/Cadastrar/index.js
- src/Pages/TipoDemanda/Cadastrar/index.js
- src/Pages/Usuarios/Cadastrar/index.js
Usa a mesma estilização das páginas de listagem nas páginas de edição
> Resolve b10t459

- src/App.js
- src/Componentes/CustomMenu/index.js
- src/Context/ContextLogin.js
- src/Pages/Demandas/Listar/index.js
- src/Pages/Termos/index.js
Contém algumas mudanças de espaçamento
> Resolve b10t470

- src/Componentes/CustomAlert/index.js
- src/Componentes/CustomMenu/index.js
- src/styles/CommonStyles.js
Adicionado botão de acesso ao menu quando a aplicação está rodando em mobile
card relacionado: https://trello.com/c/1JEaegFo/462-feature-implementar-o-layout-responsivo
> resolve b10t462

- src/Pages/Demandas/Cadastrar/Form.js
O admin tem a possibilidade de reenviar o email de avaliação
card relacionado: https://trello.com/c/re5mfGfx/480-feature-administrador-tem-permiss%C3%A3o-de-reenviar-o-e-mail-de-avalia%C3%A7%C3%A3o
> resolve b10t480

- src/Pages/Log/index.js
Alterada exibição da Data de Reunião no Log
card relacionado: https://trello.com/c/4I10NKOF/481-refactor-alterar-a-exibi%C3%A7%C3%A3o-da-data-de-reuni%C3%A3o-no-log-para-o-padr%C3%A3o-brasileiro
> resolve b10t481

- src/Pages/Demandas/Cadastrar/Form.js
Adicionado placeholder no input de horário de reunião com o formato a ser seguido 
card relacionado: https://trello.com/c/peyvWRkx/506-feature-melhorar-a-formata%C3%A7%C3%A3o-de-hor%C3%A1rios-na-escolha-do-consultor
> resolve b10t506

- src/Componentes/CustomMenu/index.js
Adicionado item no menu caso o usuário seja apenas consultor
card relacionado: https://trello.com/c/orxxM7v3/552-feature-adicionar-item-de-dados-banc%C3%A1rios-quando-o-usu%C3%A1rio-for-apenas-consultor
> resolve b10t552

- src/Pages/DadosBancarios/Cadastrar/Form.js
- src/Pages/Demandas/Cadastrar/Form.js
resolve caso em que o formulário fazia verificação antes do submit
card relacionado: https://trello.com/c/tmESyC0a/555-bug-est%C3%A3o-sendo-verificados-dados-banc%C3%A1rios-sem-que-o-usu%C3%A1rio-submeta-o-formul%C3%A1rio
> resolve b10t555

- src/Pages/Demandas/Listar/Reuniões/ReuniaoSearchBar.js
- src/Pages/Demandas/Listar/Reuniões/index.js
Adicionado filtro a tela de Reuniões
card relacionado: https://trello.com/c/iDSdQx6r/551-adicionar-os-filtros-de-demandas-na-tela-de-reuni%C3%B5es
> resolve b10t551

- src/Pages/Relatorio/Listar/index.js
Adicionado paginação na tela de relatórios
card relacionado: https://trello.com/c/iyuXqZyO/559-pagina%C3%A7%C3%A3o-do-relat%C3%B3rio-de-billing
> resolve b10t559

- src/Pages/DadosBancarios/Cadastrar/Form.js
Adicionada validação no campo do CPF
O Back agora validao o CPF
card relacionado: https://trello.com/c/3n4T6DRR/569-validar-se-o-campo-cpf-%C3%A9-valido-ao-informar-os-dados-banc%C3%A1rios-do-usu%C3%A1rio
> resolve b10t569

- src/Componentes/FormikComponents/PhoneInput.js
Adiciona possibilidade de entrar em contato com o cliente diretamente da página via whats
card relacionado: https://trello.com/c/6X9JmG1L/585-feature-implementar-o-link-para-conversa-pelo-whats-app-diretamente
> resolve b10t585

- src/Pages/Times/TipoMentores/index.js
A mesma estava desalinhada com as demais
card relacionado: https://trello.com/c/O6i1HwdZ/565-bug-tela-de-tipos-de-mentoria-desalinhada
> resolve b10t565

- src/Pages/DadosBancarios/Cadastrar/Form.js
- src/Pages/Demandas/Cadastrar/Form.js
- src/Pages/Usuarios/Cadastrar/Form.js
Quando dava submit e digitava, não saia a mensagem de que o campo estava invalido
card relacionado: https://trello.com/c/KXn9j386/566-bug-ao-aparecer-o-erro-de-obrig%C3%A1torieadade-do-campo-ap%C3%B3s-preencher-n%C3%A3o-est%C3%A1-sendo-alterado
> resolve b10t566

- src/Componentes/HourComponent/index.js
- src/Pages/Horarios/Calendario/index.js
- src/Pages/Horarios/index.js
- src/Pages/Horarios/utils.js
altera nome das rotas e atributos nas telas de horarios
card relacionado: https://trello.com/c/ZyoetEhX/586-refactor-alterar-endpoints-na-tela-de-agenda
> resolve b10t586

- src/Componentes/HourComponent/index.js
- src/Pages/Horarios/Calendario/index.js
Não estava sendo possivel voltar um horario para vazio
card relacionado: https://trello.com/c/HVUDuBuq/592-bug-n%C3%A3o-est%C3%A1-sendo-possivel-remover-um-hor%C3%A1rio-cadastrado-na-tela-de-calend%C3%A1rio
> fix b10t592

- src/Pages/Horarios/Calendario/index.js
- src/Pages/Horarios/Calendario/utils.js
- src/Pages/Horarios/utils.js
Resolvido caso em que nao atualiza o estado da página quando adicionava ou removia um item
card relacionado: https://trello.com/c/SAUBoQk6/593-bug-n%C3%A3o-est%C3%A1-atualizando-o-estado-d%C3%A1-p%C3%A1gina-quando-adiciona-ou-remove-um-novo-hor%C3%A1rio
> fix b10t593

- src/Pages/Log/index.js
Não estava sendo exibido os horarios cadastrados no Log
card relacionado: https://trello.com/c/nwdwlwML/584-bug-os-hor%C3%A1rios-na-tela-de-log-est%C3%A3o-incorretos
> fix b10t584

- src/Componentes/CustomPagination/index.js
Adicionado botoes de voltar para 1º pagina e ir para a ultima
card relacionado: https://trello.com/c/yEZCcCoH/574-feature-implementar-os-bot%C3%B5es-de-primeira-p%C3%A1gina-e-%C3%BAltima-p%C3%A1gina-na-listagem-de-registros
> resolve b10t574

- src/Pages/Log/index.js
Ajustada tela de Logs para de acordo com o padrão da aplicação
card relacionado: https://trello.com/c/uTer5IBa/576-bug-o-espa%C3%A7amentodo-das-divs-do-log-n%C3%A3o-est%C3%A3o-iguais-aos-demais-formul%C3%A1rios-de-pesquisa
> resolve b10t576

- src/Pages/Horarios/Calendario/index.js
- src/Pages/Horarios/Calendario/utils.js
Resolve caso em que duplicava o horario ao criar um novo
Resolve caso em que excluia horario ao alterar um horario existente
Refatora a função handleChange
card relacionado: https://trello.com/c/56SHjySs/603-bug-hor%C3%A1rio-aparecendo-duplicado
> resolve b10t603

- src/Componentes/HourComponent/index.js
- src/styles/CommonStyles.js
Alinha os components nas páginas de horarios
card relacionado: https://trello.com/c/6SqOk7vf/612-refactor-organizar-a-tela-de-agendas-para-quando-a-resolu%C3%A7%C3%A3o-for-para-mobile
> resolve b10t612

- src/Componentes/HourComponent/index.js
- src/Pages/Horarios/Calendario/utils.js
Resolve caso em que ao excluir um item novo, com 2 ou mais outros horarios na tela, não excluia o item
Corrigido caso em que não era possivel criar horario se começasse do horario final
Refatorada algumas funções
card relacionado: https://trello.com/c/mdLlxid9/614-erro-ao-agendar-hor%C3%A1rio
> resolve b10t614

- src/Pages/Demandas/Cadastrar/Form.js
Resolve b10t621
Card relacionado: https://trello.com/c/t2jMWGeL/621-feature-avalia%C3%A7%C3%A3o-para-ser-feita-pelo-admin
> Feat(Demanda): Adiciona modal e botão de avaliação para admin avaliar reunião

- src/Pages/Downloads/index.js
Altera cor do botão na tela de Downloads para a cor padrão da aplicação
card relacionado: https://trello.com/c/EOOHEVYP/620-refactor-alterar-cor-do-bot%C3%A3o-da-tela-de-downloads
> resolve b10t620

- src/Pages/DadosBancarios/Cadastrar/Form.js
Dá a possibilidade do cliente digitar -/ nos inputs de agencia e conta bancária
ps: Leo falou que não era necessário criar uma mascára para tratar isso, visto que tem padrão diferentes 
card relacionado: https://trello.com/c/cuLFRQLh/619-feature-modifica%C3%A7%C3%A3o-nos-dados-banc%C3%A1rios
> Refactor(DadosBancarios): Agora pode ser adicionado digitos aos campos

- src/Pages/Horarios/index.js
- src/Pages/Horarios/utils.js
Adicionado o dia de sabádo aos seletores de agendamento
card relacionado: https://trello.com/c/OW0wfG7u/622-permitir-que-os-usu%C3%A1rios-cadastrem-hor%C3%A1rios-para-agendamento-no-s%C3%A1bado
> resolve b10t622

- src/Pages/Horarios/Calendario/utils.js
- src/Pages/Horarios/index.js
- src/Pages/Horarios/utils.js
Resolve caso que não enviava só um horário
Cria novas funções como forma de refatorar o código
card relacionado: https://trello.com/c/b8S03c53/590-em-agenda-est%C3%A1-sendo-exibida-mensagem-de-sucesso-ao-tentar-definir-somente-um-hor%C3%A1rio-in%C3%ADcio-ou-fim
> resolve b10t590

- src/Componentes/SearchBar/index.js
- src/Pages/Demandas/Listar/DemandSearchBar.js
Adicionado seletores de datas para quando o status for comparecido
card relacionado: https://trello.com/c/AaS6pny9/624-feature-exibir-o-per%C3%ADodo-de-data-quando-o-status-selecionado-da-demanda-for-comparecido
> resolve b10t624

- src/Pages/Horarios/Calendario/index.js
Corrigido bug que não era possivel apagar horario pelo seletor na tela de Calendario
Corrigido caso em que o alerta de erro aparecia com a cor de sucesso
Criada uma nova função para o tratamento de envio de dias 
card relacionado: https://trello.com/c/tTZaufAQ/632-bug-usu%C3%A1rio-n%C3%A3o-est%C3%A1-conseguindo-remover-o-dia-da-agenda
> resolve b10t632

- src/Componentes/CustomMenu/index.js
- src/styles/CommonStyles.js
Adiciona numero da versão na aplicação
card relacionado: https://trello.com/c/wexkFFSy/474-feature-informa-a-vers%C3%A3o-da-aplica%C3%A7%C3%A3o-em-algum-lugar-da-aplica%C3%A7%C3%A3o
> resolve b10t474

- src/Pages/Demandas/Cadastrar/Form.js
Resolve caso em que o seletor de mensagens e os dados não carregavam em alguns casos
Foi adicionado um loading na página que soluciona o problema
card relacionado: https://trello.com/c/xZxIjOD1/484-bug-algumas-vezes-os-dropdown-lists-n%C3%A3o-tem-os-valores-carregados
> resolve b10t484

- src/Routes/admin.routes.js
- src/Routes/index.js
- src/Routes/user.routes.js
- src/Services/api.js
Usuários que não são admin não conseguem mais acessar as rotas para admin, dá 404 e é redirecionado
card relacionado: https://trello.com/c/6AMEaCV5/633-refactor-separar-as-rotas-dos-usu%C3%A1rios-de-acordo-com-o-seu-acesso-a-aplica%C3%A7%C3%A3o
> resolve b10t633

- src/Pages/Demandas/Cadastrar/Form.js
Ao adicionar o loading na pagina, não estava sendo possivel criar uma demanda 
card relacionado: https://trello.com/c/cutcZSII/638-bug-n%C3%A3o-est%C3%A1-sendo-possivel-criar-uma-nova-demanda
> resolve b10t638

- src/Componentes/CustomAlert/index.js
resolve [b10t13](https://trello.com/c/eC6dE7ke/13-sucesso-ao-editar-uma-demanda)
Alerta não limpava o alerta anterior para atualizar o feedback da solicitação
> Fix(Alert): Limpa alerta anterior para mostrar novo

- src/Componentes/CustomFileInputField/index.js
- src/Pages/DadosBancarios/Cadastrar/index.js
- src/Pages/Demandas/Cadastrar/Form.js
- src/Pages/Times/TipoMentores/index.js
- src/Pages/Usuarios/UsuarioBadges/index.js
- src/Pages/Usuarios/UsuarioCompanhia/index.js
- src/Pages/Usuarios/UsuarioJornadas/index.js
- src/Pages/Usuarios/UsuarioTimes/index.js
- src/Pages/Usuarios/UsuarioTipoDemanda/index.js
[b10t11](https://trello.com/c/uKX7zI31/11-bfree-filtro-das-demandas),  
[b10t13](https://trello.com/c/eC6dE7ke/13-sucesso-ao-editar-uma-demanda)
[b10t14](https://trello.com/c/Pbhk9NVR/14-separar-campos-de-dados-de-qualificação-e-observações),
> Fix(Varios): Filtro das demands, Separação de campos,  upload excel

- package.json
- src/Componentes/ListMessages/index.js
- src/Pages/Demandas/Cadastrar/Form.js
- src/Services/api.js
Adiciona funcionalidade de retry
> B10t(15,16)
